[package]
name = "ow_damage_calc_web"
version = "0.1.0"
authors = ["iguto <clc.iguto@gmail.com>"]

[dependencies]
# strum = "0.8.0"
# strum_macros = "0.8.0"
# serde = "1"
# serde_derive = "1"
chrono = "0.4.0"

[dependencies.yew]
git = "https://github.com/DenisKolodin/yew.git"